import { trpc } from "@/lib/trpc";
import { useMemo, useState } from "react";
import { toast } from "sonner";
import { Boxes, Building2, Cable, Check, ClipboardCheck, HardHat, Map, PackagePlus, Pencil, Plus, RefreshCw, Route, Settings2, Trash2, UserCheck, Wrench, X } from "lucide-react";

type Resource = "department" | "project" | "drum" | "equipment" | "permit" | "route";
type Form = Record<string, string>;
const emptyForm: Form = {};
function toInputDate(value: Date | string | null | undefined) { return value ? new Date(value).toISOString().slice(0, 10) : ""; }
function readableStatus(value: string) { const labels: Record<string, string> = { planning: "تخطيط", active: "نشط", paused: "متوقف", completed: "مكتمل", available: "متاح", allocated: "مخصص", low_stock: "منخفض", depleted: "نافد", ready: "جاهز", assigned: "مُعيّن", maintenance: "صيانة", calibration_due: "معايرة مطلوبة", valid: "ساري", expiring: "ينتهي قريباً", expired: "منتهي", under_renewal: "قيد التجديد", civil: "أعمال مدنية", pulling: "سحب كابل", splicing: "لحام", otdr: "فحص OTDR", handover: "تسليم", blocked: "محظور" }; return labels[value] ?? value; }
function statusTone(value: string) { return value === "expired" || value === "blocked" || value === "depleted" ? "border-rose-400/20 bg-rose-400/10 text-rose-200" : value === "expiring" || value === "low_stock" || value === "calibration_due" ? "border-amber-400/20 bg-amber-400/10 text-amber-100" : "border-emerald-400/20 bg-emerald-400/10 text-emerald-200"; }
function Modal({ title, children, onClose }: { title: string; children: React.ReactNode; onClose: () => void }) { return <div className="fixed inset-0 z-50 grid place-items-center bg-[#02070b]/75 p-4 backdrop-blur-sm"><div dir="rtl" className="max-h-[92vh] w-full max-w-2xl overflow-y-auto rounded-2xl border border-white/10 bg-[#101a25] shadow-2xl"><div className="flex items-center justify-between border-b border-white/[0.07] px-6 py-4"><h2 className="text-lg font-bold text-white">{title}</h2><button onClick={onClose} className="rounded-lg p-2 text-slate-400 hover:bg-white/5 hover:text-white"><X size={18} /></button></div>{children}</div></div>; }

export default function Operations() {
  const initialTab = new URLSearchParams(window.location.search).get("tab") ?? "assets";
  const [tab, setTab] = useState(initialTab);
  const [editor, setEditor] = useState<Resource | "renew" | "assign" | null>(null);
  const [editId, setEditId] = useState<number | null>(null);
  const [form, setForm] = useState<Form>(emptyForm);
  const [assignmentId, setAssignmentId] = useState<number | null>(null);
  const [renewId, setRenewId] = useState<number | null>(null);
  const utils = trpc.useUtils();
  const query = trpc.operations.list.useQuery();
  const overview = trpc.operations.overview.useQuery();
  const data = query.data;
  const employees = data?.employees ?? [];
  const projects = data?.projects ?? [];
  const invalidate = async () => { await Promise.all([utils.operations.list.invalidate(), utils.operations.overview.invalidate(), utils.workforce.list.invalidate()]); };
  const hook = <T,>(mutation: T) => mutation;
  const createDepartment = trpc.operations.createDepartment.useMutation({ onSuccess: invalidate, onError: e => toast.error(e.message) });
  const updateDepartment = trpc.operations.updateDepartment.useMutation({ onSuccess: invalidate, onError: e => toast.error(e.message) });
  const deleteDepartment = trpc.operations.deleteDepartment.useMutation({ onSuccess: invalidate, onError: e => toast.error(e.message) });
  const createProject = trpc.operations.createProject.useMutation({ onSuccess: invalidate, onError: e => toast.error(e.message) });
  const updateProject = trpc.operations.updateProject.useMutation({ onSuccess: invalidate, onError: e => toast.error(e.message) });
  const deleteProject = trpc.operations.deleteProject.useMutation({ onSuccess: invalidate, onError: e => toast.error(e.message) });
  const createDrum = trpc.operations.createDrum.useMutation({ onSuccess: invalidate, onError: e => toast.error(e.message) });
  const updateDrum = trpc.operations.updateDrum.useMutation({ onSuccess: invalidate, onError: e => toast.error(e.message) });
  const deleteDrum = trpc.operations.deleteDrum.useMutation({ onSuccess: invalidate, onError: e => toast.error(e.message) });
  const createEquipment = trpc.operations.createEquipment.useMutation({ onSuccess: invalidate, onError: e => toast.error(e.message) });
  const updateEquipment = trpc.operations.updateEquipment.useMutation({ onSuccess: invalidate, onError: e => toast.error(e.message) });
  const deleteEquipment = trpc.operations.deleteEquipment.useMutation({ onSuccess: invalidate, onError: e => toast.error(e.message) });
  const assignEquipment = trpc.operations.assignEquipment.useMutation({ onSuccess: invalidate, onError: e => toast.error(e.message) });
  const releaseEquipment = trpc.operations.releaseEquipment.useMutation({ onSuccess: invalidate, onError: e => toast.error(e.message) });
  const createPermit = trpc.operations.createPermit.useMutation({ onSuccess: invalidate, onError: e => toast.error(e.message) });
  const updatePermit = trpc.operations.updatePermit.useMutation({ onSuccess: invalidate, onError: e => toast.error(e.message) });
  const renewPermit = trpc.operations.renewPermit.useMutation({ onSuccess: invalidate, onError: e => toast.error(e.message) });
  const deletePermit = trpc.operations.deletePermit.useMutation({ onSuccess: invalidate, onError: e => toast.error(e.message) });
  const createRoute = trpc.operations.createRoute.useMutation({ onSuccess: invalidate, onError: e => toast.error(e.message) });
  const updateRoute = trpc.operations.updateRoute.useMutation({ onSuccess: invalidate, onError: e => toast.error(e.message) });
  const deleteRoute = trpc.operations.deleteRoute.useMutation({ onSuccess: invalidate, onError: e => toast.error(e.message) });
  const refreshPermits = trpc.operations.refreshPermitStatuses.useMutation({ onSuccess: async result => { toast.success(`تم تحديث ${result.changed} تصاريح.`); await invalidate(); }, onError: e => toast.error(e.message) });

  const changeTab = (next: string) => { window.history.replaceState(null, "", `/operations?tab=${next}`); setTab(next); };
  const open = (resource: Resource, item?: Record<string, unknown>) => { setEditor(resource); setEditId(item ? Number(item.id) : null); if (!item) { setForm({}); return; } setForm(Object.fromEntries(Object.entries(item).map(([key, value]) => [key, value instanceof Date || key.toLowerCase().includes("date") || key.toLowerCase().includes("dueat") ? toInputDate(value as Date | string | null) : value == null ? "" : String(value)]))); };
  const done = async (message: string) => { toast.success(message); setEditor(null); setEditId(null); setForm({}); await invalidate(); };
  const number = (key: string) => Number(form[key] || 0);
  const nullableId = (key: string) => form[key] ? Number(form[key]) : null;
  const submit = () => {
    if (!editor || editor === "renew" || editor === "assign") return;
    if (editor === "department") { const payload = { name: form.name, code: form.code, managerName: form.managerName || null, active: (form.active || "yes") as "yes" | "no" }; editId ? updateDepartment.mutate({ id: editId, ...payload }, { onSuccess: () => done("تم تعديل القسم.") }) : createDepartment.mutate(payload, { onSuccess: () => done("تمت إضافة القسم.") }); }
    if (editor === "project") { const payload = { code: form.code, name: form.name, clientName: form.clientName || null, status: (form.status || "planning") as "planning" | "active" | "paused" | "completed", startDate: form.startDate || null, targetDate: form.targetDate || null }; editId ? updateProject.mutate({ id: editId, ...payload }, { onSuccess: () => done("تم تعديل المشروع.") }) : createProject.mutate(payload, { onSuccess: () => done("تمت إضافة المشروع.") }); }
    if (editor === "drum") { const payload = { drumId: form.drumId, fiberSpec: form.fiberSpec, coreCount: number("coreCount"), supplier: form.supplier || null, totalMeters: number("totalMeters"), remainingMeters: number("remainingMeters"), minimumMeters: number("minimumMeters"), assignedProjectId: nullableId("assignedProjectId"), storageLocation: form.storageLocation }; editId ? updateDrum.mutate({ id: editId, ...payload }, { onSuccess: () => done("تم تعديل البكرة.") }) : createDrum.mutate(payload, { onSuccess: () => done("تمت إضافة البكرة.") }); }
    if (editor === "equipment") { const payload = { assetTag: form.assetTag, name: form.name, category: (form.category || "other") as "splicer" | "otdr" | "power_meter" | "safety" | "other", serialNumber: form.serialNumber || null, calibrationDueAt: form.calibrationDueAt || null, status: (form.status || "ready") as "ready" | "assigned" | "maintenance" | "calibration_due", assignedEmployeeId: nullableId("assignedEmployeeId") }; editId ? updateEquipment.mutate({ id: editId, ...payload }, { onSuccess: () => done("تم تعديل المعدة.") }) : createEquipment.mutate(payload, { onSuccess: () => done("تمت إضافة المعدة.") }); }
    if (editor === "permit") { const payload = { permitNo: form.permitNo, issuer: (form.issuer || "other") as "public_works" | "traffic" | "municipality" | "other", routeName: form.routeName, projectId: nullableId("projectId"), startDate: form.startDate, expiryDate: form.expiryDate, renewalReference: form.renewalReference || null, notes: form.notes || null }; editId ? updatePermit.mutate({ id: editId, ...payload }, { onSuccess: () => done("تم تعديل التصريح.") }) : createPermit.mutate(payload, { onSuccess: () => done("تم إصدار التصريح.") }); }
    if (editor === "route") { const payload = { routeCode: form.routeCode, name: form.name, projectId: nullableId("projectId"), contractorName: form.contractorName || null, stage: (form.stage || "civil") as "civil" | "pulling" | "splicing" | "otdr" | "handover", progressPercent: number("progressPercent"), permitId: nullableId("permitId"), status: (form.status || "active") as "active" | "blocked" | "completed" }; editId ? updateRoute.mutate({ id: editId, ...payload }, { onSuccess: () => done("تم تعديل المسار.") }) : createRoute.mutate(payload, { onSuccess: () => done("تمت إضافة المسار.") }); }
  };
  const remove = (resource: Resource, id: number) => { if (!confirm("سيتم حذف السجل نهائياً. هل تريد المتابعة؟")) return; const mutation = resource === "department" ? deleteDepartment : resource === "project" ? deleteProject : resource === "drum" ? deleteDrum : resource === "equipment" ? deleteEquipment : resource === "permit" ? deletePermit : deleteRoute; mutation.mutate({ id }, { onSuccess: () => { toast.success("تم حذف السجل."); invalidate(); } }); };

  const fields = useMemo(() => ({
    department: [["name", "اسم القسم"], ["code", "الرمز"], ["managerName", "مدير القسم"], ["active", "الحالة", "select", ["yes", "مفعل"], ["no", "موقوف"]]],
    project: [["code", "رمز المشروع"], ["name", "اسم المشروع"], ["clientName", "العميل"], ["status", "الحالة", "select", ["planning", "تخطيط"], ["active", "نشط"], ["paused", "متوقف"], ["completed", "مكتمل"]], ["startDate", "تاريخ البدء", "date"], ["targetDate", "تاريخ الاستهداف", "date"]],
    drum: [["drumId", "رقم البكرة"], ["fiberSpec", "مواصفة الكابل"], ["coreCount", "عدد الأنوية", "number"], ["supplier", "المورد"], ["totalMeters", "الطول الإجمالي (م)", "number"], ["remainingMeters", "الرصيد المتبقي (م)", "number"], ["minimumMeters", "حد التنبيه (م)", "number"], ["assignedProjectId", "المشروع", "project"], ["storageLocation", "موقع التخزين"]],
    equipment: [["assetTag", "رمز الأصل"], ["name", "اسم المعدة"], ["category", "الفئة", "select", ["splicer", "جهاز لحام"], ["otdr", "OTDR"], ["power_meter", "Power Meter"], ["safety", "سلامة"], ["other", "أخرى"]], ["serialNumber", "الرقم التسلسلي"], ["calibrationDueAt", "تاريخ المعايرة", "date"], ["status", "الحالة", "select", ["ready", "جاهزة"], ["assigned", "معينة"], ["maintenance", "صيانة"], ["calibration_due", "معايرة مطلوبة"]], ["assignedEmployeeId", "الموظف المسؤول", "employee"]],
    permit: [["permitNo", "رقم التصريح"], ["issuer", "الجهة المصدرة", "select", ["public_works", "الأشغال العامة"], ["traffic", "المرور"], ["municipality", "البلدية"], ["other", "أخرى"]], ["routeName", "المسار"], ["projectId", "المشروع", "project"], ["startDate", "تاريخ البداية", "date"], ["expiryDate", "تاريخ الانتهاء", "date"], ["renewalReference", "مرجع التجديد"], ["notes", "ملاحظات"]],
    route: [["routeCode", "رمز المسار"], ["name", "اسم المسار"], ["projectId", "المشروع", "project"], ["contractorName", "المقاول"], ["stage", "المرحلة", "select", ["civil", "أعمال مدنية"], ["pulling", "سحب"], ["splicing", "لحام"], ["otdr", "OTDR"], ["handover", "تسليم"]], ["progressPercent", "نسبة الإنجاز", "number"], ["permitId", "التصريح", "permit"], ["status", "الحالة", "select", ["active", "نشط"], ["blocked", "محظور"], ["completed", "مكتمل"]]],
  }), [projects, employees, data?.permits]);
  const label = { department: "قسم", project: "مشروع", drum: "بكرة كابل", equipment: "معدة", permit: "تصريح", route: "مسار" };
  const control = (field: any[]) => { const [key, text, kind, ...options] = field; const value = form[key] ?? ""; if (kind === "select") return <label className="field" key={key}><span>{text}</span><select value={value} onChange={e => setForm({ ...form, [key]: e.target.value })}>{options.map((opt: string[]) => <option key={opt[0]} value={opt[0]}>{opt[1]}</option>)}</select></label>; if (kind === "project" || kind === "employee" || kind === "permit") { const rows = kind === "project" ? projects : kind === "employee" ? employees : data?.permits ?? []; return <label className="field" key={key}><span>{text}</span><select value={value} onChange={e => setForm({ ...form, [key]: e.target.value })}><option value="">غير محدد</option>{rows.map((row: any) => <option key={row.id} value={row.id}>{row.name || (row.firstName ? `${row.firstName} ${row.lastName}` : row.permitNo || "—")}</option>)}</select></label>; } return <label className="field" key={key}><span>{text}</span><input type={kind === "date" ? "date" : kind === "number" ? "number" : "text"} value={value} onChange={e => setForm({ ...form, [key]: e.target.value })} /></label>; };
  if (query.isLoading) return <div className="p-10 text-center text-sm text-slate-400">جارٍ تحميل العمليات...</div>;
  if (query.error) return <div className="rounded-2xl border border-rose-400/20 bg-rose-400/10 p-6 text-rose-100">تعذر تحميل العمليات: {query.error.message}</div>;
  const tabItems = [{ id: "assets", label: "الأصول والمخزون", icon: Boxes }, { id: "permits", label: "التصاريح", icon: ClipboardCheck }, { id: "routes", label: "المسارات", icon: Route }, { id: "structure", label: "الأقسام والمشاريع", icon: Building2 }];
  const renderActions = (resource: Resource, row: Record<string, any>, extra?: React.ReactNode) => <div className="flex items-center gap-1">{extra}<button onClick={() => open(resource, row)} className="rounded-lg p-2 text-slate-400 hover:bg-white/[0.06] hover:text-[#7cc5ff]"><Pencil size={15} /></button><button onClick={() => remove(resource, row.id)} className="rounded-lg p-2 text-slate-500 hover:bg-rose-400/10 hover:text-rose-300"><Trash2 size={15} /></button></div>;
  return <div dir="rtl" className="mx-auto max-w-[1550px] space-y-6 pb-10"><header className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-[11px] font-bold tracking-[0.18em] text-[#7cc5ff]">تشغيل البنية التحتية</p><h1 className="mt-2 text-3xl font-bold text-white">الأصول والتصاريح والمسارات</h1><p className="mt-2 max-w-2xl text-sm leading-7 text-slate-400">أدر كل سجل تشغيلي بإجراءات إضافة وتعديل وحذف وتخصيص وتجديد موثقة داخل FiberOps.</p></div><div className="flex gap-2"><button onClick={() => refreshPermits.mutate()} className="inline-flex items-center gap-2 rounded-xl border border-white/10 px-3.5 py-2.5 text-xs font-bold text-slate-200 hover:bg-white/[0.05]"><RefreshCw size={15} className={refreshPermits.isPending ? "animate-spin" : ""} />تحديث حالة التصاريح</button></div></header><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><div className="rounded-2xl border border-white/[0.07] bg-[#101a25] p-4"><HardHat size={18} className="text-[#7cc5ff]" /><strong className="mt-4 block font-mono text-2xl text-white">{overview.data?.employees ?? 0}</strong><span className="text-xs text-slate-500">عمالة ميدانية نشطة</span></div><div className="rounded-2xl border border-white/[0.07] bg-[#101a25] p-4"><Cable size={18} className="text-amber-300" /><strong className="mt-4 block font-mono text-2xl text-white">{overview.data?.lowStockDrums ?? 0}</strong><span className="text-xs text-slate-500">بكرات منخفضة / نافدة</span></div><div className="rounded-2xl border border-white/[0.07] bg-[#101a25] p-4"><Wrench size={18} className="text-amber-300" /><strong className="mt-4 block font-mono text-2xl text-white">{overview.data?.calibrationDue ?? 0}</strong><span className="text-xs text-slate-500">معدات للمعايرة</span></div><div className="rounded-2xl border border-white/[0.07] bg-[#101a25] p-4"><Map size={18} className="text-rose-300" /><strong className="mt-4 block font-mono text-2xl text-white">{overview.data?.blockedRoutes ?? 0}</strong><span className="text-xs text-slate-500">مسارات محظورة</span></div></section><div className="flex flex-wrap gap-2 border-b border-white/[0.07] pb-4">{tabItems.map(item => { const Icon = item.icon; return <button key={item.id} onClick={() => changeTab(item.id)} className={`inline-flex items-center gap-2 rounded-xl px-3.5 py-2.5 text-sm font-bold transition ${tab === item.id ? "bg-[#2F9BFF]/12 text-[#9fd4ff]" : "text-slate-400 hover:bg-white/[0.04] hover:text-white"}`}><Icon size={16} />{item.label}</button>; })}</div>
    {tab === "assets" && <section className="space-y-5"><ResourceHeader title="بكرات الكابلات" description="الرصيد الفعلي، الحد الأدنى، ومشروع التخصيص." onAdd={() => open("drum")} addText="إضافة بكرة" /><div className="overflow-x-auto rounded-2xl border border-white/[0.07] bg-[#101a25]"><table className="w-full min-w-[880px] text-right"><thead className="bg-white/[0.025] text-[10px] tracking-[0.12em] text-slate-500"><tr><th className="px-5 py-3">البكرة</th><th className="px-5 py-3">المواصفة</th><th className="px-5 py-3">الرصيد</th><th className="px-5 py-3">الموقع</th><th className="px-5 py-3">الحالة</th><th /></tr></thead><tbody className="divide-y divide-white/[0.06]">{(data?.drums ?? []).map(row => <tr key={row.id}><td className="px-5 py-4 font-mono text-xs text-[#7cc5ff]">{row.drumId}</td><td className="px-5 py-4 text-xs text-slate-200">{row.fiberSpec}<span className="mr-2 text-slate-500">{row.coreCount}-Core</span></td><td className="px-5 py-4 font-mono text-xs text-white">{row.remainingMeters.toLocaleString()} / {row.totalMeters.toLocaleString()} م</td><td className="px-5 py-4 text-xs text-slate-400">{row.storageLocation}</td><td className="px-5 py-4"><span className={`rounded-full border px-2.5 py-1 text-[10px] ${statusTone(row.status)}`}>{readableStatus(row.status)}</span></td><td className="px-5 py-4">{renderActions("drum", row)}</td></tr>)}</tbody></table></div><ResourceHeader title="معدات الفحص واللحام" description="حالة المعايرة والتعيين للعامل." onAdd={() => open("equipment")} addText="إضافة معدة" /><div className="grid gap-3 md:grid-cols-2">{(data?.equipment ?? []).map(row => <article key={row.id} className="rounded-2xl border border-white/[0.07] bg-[#101a25] p-5"><div className="flex items-start justify-between"><div><span className="font-mono text-xs text-[#7cc5ff]">{row.assetTag}</span><h3 className="mt-2 font-bold text-white">{row.name}</h3><p className="mt-1 text-xs text-slate-500">{row.serialNumber ?? "بدون رقم تسلسلي"}</p></div>{renderActions("equipment", row, row.assignedEmployeeId ? <button onClick={() => releaseEquipment.mutate({ id: row.id })} className="rounded-lg px-2 py-1 text-[10px] font-bold text-amber-200 hover:bg-amber-400/10">إلغاء</button> : <button onClick={() => { setAssignmentId(row.id); setEditor("assign"); }} className="rounded-lg px-2 py-1 text-[10px] font-bold text-[#9fd4ff] hover:bg-[#2F9BFF]/10">تعيين</button>)}</div><div className="mt-5 flex items-center justify-between border-t border-white/[0.07] pt-3"><span className={`rounded-full border px-2.5 py-1 text-[10px] ${statusTone(row.status)}`}>{readableStatus(row.status)}</span><span className="text-[10px] text-slate-500">معايرة: {toInputDate(row.calibrationDueAt) || "—"}</span></div></article>)}</div></section>}
    {tab === "permits" && <section><ResourceHeader title="التصاريح والاعتمادات" description="الحالة تحسب من تاريخ الانتهاء وتدعم إجراء التجديد." onAdd={() => open("permit")} addText="إصدار تصريح" /><div className="overflow-x-auto rounded-2xl border border-white/[0.07] bg-[#101a25]"><table className="w-full min-w-[820px] text-right"><thead className="bg-white/[0.025] text-[10px] tracking-[0.12em] text-slate-500"><tr><th className="px-5 py-3">التصريح</th><th className="px-5 py-3">الجهة</th><th className="px-5 py-3">المسار</th><th className="px-5 py-3">الانتهاء</th><th className="px-5 py-3">الحالة</th><th /></tr></thead><tbody className="divide-y divide-white/[0.06]">{(data?.permits ?? []).map(row => <tr key={row.id}><td className="px-5 py-4 font-mono text-xs text-[#7cc5ff]">{row.permitNo}</td><td className="px-5 py-4 text-xs text-slate-300">{readableStatus(row.issuer)}</td><td className="px-5 py-4 text-sm font-semibold text-white">{row.routeName}</td><td className="px-5 py-4 text-xs text-slate-400">{toInputDate(row.expiryDate)}</td><td className="px-5 py-4"><span className={`rounded-full border px-2.5 py-1 text-[10px] ${statusTone(row.status)}`}>{readableStatus(row.status)}</span></td><td className="px-5 py-4">{renderActions("permit", row, <button onClick={() => { setRenewId(row.id); setForm({ expiryDate: toInputDate(row.expiryDate), renewalReference: "" }); setEditor("renew"); }} className="rounded-lg px-2 py-1 text-[10px] font-bold text-[#9fd4ff] hover:bg-[#2F9BFF]/10">تجديد</button>)}</td></tr>)}</tbody></table></div></section>}
    {tab === "routes" && <section><ResourceHeader title="المسارات التنفيذية" description="ربط مراحل التنفيذ بالتقدم والمشروع والتصريح." onAdd={() => open("route")} addText="إضافة مسار" /><div className="overflow-x-auto rounded-2xl border border-white/[0.07] bg-[#101a25]"><table className="w-full min-w-[780px] text-right"><thead className="bg-white/[0.025] text-[10px] tracking-[0.12em] text-slate-500"><tr><th className="px-5 py-3">المسار</th><th className="px-5 py-3">المقاول</th><th className="px-5 py-3">المرحلة</th><th className="px-5 py-3">الإنجاز</th><th className="px-5 py-3">الحالة</th><th /></tr></thead><tbody className="divide-y divide-white/[0.06]">{(data?.routes ?? []).map(row => <tr key={row.id}><td className="px-5 py-4"><strong className="block text-sm text-white">{row.name}</strong><span className="font-mono text-[10px] text-[#7cc5ff]">{row.routeCode}</span></td><td className="px-5 py-4 text-xs text-slate-400">{row.contractorName ?? "—"}</td><td className="px-5 py-4 text-xs text-slate-300">{readableStatus(row.stage)}</td><td className="px-5 py-4"><div className="flex items-center gap-2"><div className="h-1.5 w-20 overflow-hidden rounded-full bg-white/[0.08]"><div className="h-full rounded-full bg-[#2F9BFF]" style={{ width: `${row.progressPercent}%` }} /></div><span className="font-mono text-xs text-white">{row.progressPercent}%</span></div></td><td className="px-5 py-4"><span className={`rounded-full border px-2.5 py-1 text-[10px] ${statusTone(row.status)}`}>{readableStatus(row.status)}</span></td><td className="px-5 py-4">{renderActions("route", row)}</td></tr>)}</tbody></table></div></section>}
    {tab === "structure" && <section className="grid gap-5 xl:grid-cols-2"><div><ResourceHeader title="الأقسام" description="تصنيف موارد الشركة والمالكين التشغيليين." onAdd={() => open("department")} addText="إضافة قسم" /><div className="space-y-3">{(data?.departments ?? []).map(row => <article key={row.id} className="flex items-center justify-between rounded-2xl border border-white/[0.07] bg-[#101a25] p-4"><div><strong className="text-sm text-white">{row.name}</strong><span className="mr-2 font-mono text-[10px] text-[#7cc5ff]">{row.code}</span><p className="mt-1 text-xs text-slate-500">{row.managerName ?? "دون مدير محدد"}</p></div>{renderActions("department", row)}</article>)}</div></div><div><ResourceHeader title="المشاريع" description="مشاريع FTTH المرتبطة بالعمالة والأصول والتصاريح." onAdd={() => open("project")} addText="إضافة مشروع" /><div className="space-y-3">{projects.map(row => <article key={row.id} className="flex items-center justify-between rounded-2xl border border-white/[0.07] bg-[#101a25] p-4"><div><strong className="text-sm text-white">{row.name}</strong><span className="mr-2 font-mono text-[10px] text-[#7cc5ff]">{row.code}</span><p className="mt-1 text-xs text-slate-500">{row.clientName ?? "دون عميل محدد"}</p></div>{renderActions("project", row)}</article>)}</div></div></section>}
    {editor && editor !== "renew" && editor !== "assign" && <Modal title={`${editId ? "تعديل" : "إضافة"} ${label[editor]}`} onClose={() => setEditor(null)}><div className="grid gap-4 p-6 sm:grid-cols-2">{(fields[editor] as any[]).map(control)}<div className="sm:col-span-2 flex justify-end gap-3 border-t border-white/[0.07] pt-5"><button onClick={() => setEditor(null)} className="rounded-xl border border-white/10 px-4 py-2.5 text-sm font-bold text-slate-300">إلغاء</button><button onClick={submit} className="inline-flex items-center gap-2 rounded-xl bg-[#2F9BFF] px-4 py-2.5 text-sm font-bold text-[#06111b]"><Check size={16} />حفظ</button></div></div></Modal>}
    {editor === "renew" && renewId && <Modal title="تجديد التصريح" onClose={() => setEditor(null)}><div className="space-y-4 p-6"><label className="field"><span>تاريخ الانتهاء الجديد</span><input type="date" value={form.expiryDate ?? ""} onChange={e => setForm({ ...form, expiryDate: e.target.value })} /></label><label className="field"><span>مرجع التجديد</span><input value={form.renewalReference ?? ""} onChange={e => setForm({ ...form, renewalReference: e.target.value })} /></label><div className="flex justify-end gap-3"><button onClick={() => setEditor(null)} className="rounded-xl border border-white/10 px-4 py-2.5 text-sm font-bold text-slate-300">إلغاء</button><button onClick={() => renewPermit.mutate({ id: renewId, expiryDate: form.expiryDate, renewalReference: form.renewalReference || null }, { onSuccess: () => done("تم تجديد التصريح.") })} className="rounded-xl bg-[#2F9BFF] px-4 py-2.5 text-sm font-bold text-[#06111b]">اعتماد التجديد</button></div></div></Modal>}
    {editor === "assign" && assignmentId && <Modal title="تعيين معدة لعامل" onClose={() => setEditor(null)}><div className="space-y-4 p-6"><label className="field"><span>العامل المسؤول</span><select value={form.employeeId ?? ""} onChange={e => setForm({ ...form, employeeId: e.target.value })}><option value="">اختر العامل</option>{employees.map(row => <option key={row.id} value={row.id}>{row.firstName} {row.lastName} — {row.employeeNo}</option>)}</select></label><div className="flex justify-end gap-3"><button onClick={() => setEditor(null)} className="rounded-xl border border-white/10 px-4 py-2.5 text-sm font-bold text-slate-300">إلغاء</button><button onClick={() => form.employeeId && assignEquipment.mutate({ id: assignmentId, employeeId: Number(form.employeeId) }, { onSuccess: () => done("تم تعيين المعدة.") })} className="rounded-xl bg-[#2F9BFF] px-4 py-2.5 text-sm font-bold text-[#06111b]">تأكيد التعيين</button></div></div></Modal>}
  </div>;
}

function ResourceHeader({ title, description, onAdd, addText }: { title: string; description: string; onAdd: () => void; addText: string }) { return <div className="mb-4 flex items-end justify-between"><div><h2 className="font-bold text-white">{title}</h2><p className="mt-1 text-xs text-slate-500">{description}</p></div><button onClick={onAdd} className="inline-flex items-center gap-2 rounded-xl border border-[#2F9BFF]/20 bg-[#2F9BFF]/[0.07] px-3 py-2 text-xs font-bold text-[#9fd4ff] hover:bg-[#2F9BFF]/[0.14]"><Plus size={15} />{addText}</button></div>; }
